
# version 30001

data_job

_rlnJobType                            18
_rlnJobIsContinue                       0
 

# version 30001

data_joboptions_values

loop_ 
_rlnJobOptionVariable #1 
_rlnJobOptionValue #2 
ctf_intact_first_peak         No 
do_combine_thru_disc         No 
do_ctf_correction        Yes 
   do_pad1         No 
do_parallel_discio        Yes 
do_preread_images        Yes 
  do_queue         No 
do_solvent        Yes 
   fn_cont         "" 
    fn_img Select/job014/particles.star 
   gpu_ids    4:5:6:7 
min_dedicated         24 
nr_classes          1 
    nr_mpi          5 
   nr_pool         30 
nr_threads          6 
offset_range          6 
offset_step          2 
other_args         "" 
particle_diameter        200 
      qsub       qsub 
qsubscript /public/EM/RELION/relion/bin/relion_qsub.csh 
 queuename    openmpi 
  sampling 15__degrees 
scratch_dir         "" 
sgd_fin_iter         25 
sgd_fin_resol         15 
sgd_fin_subset_size        500 
sgd_inbetween_iter        100 
sgd_ini_iter         25 
sgd_ini_resol         35 
sgd_ini_subset_size        100 
sgd_sigma2fudge_halflife         -1 
sgd_write_iter         10 
  sym_name         C1 
   use_gpu        Yes 
 

# version 30001

data_joboptions_full_definition

loop_ 
_rlnJobOptionVariable #1 
_rlnJobOptionGUILabel #2 
_rlnJoboptionType #3 
_rlnJobOptionDefaultValue #4 
_rlnJobOptionSliderMin #5 
_rlnJobOptionSliderMax #6 
_rlnJobOptionSliderStep #7 
_rlnJobOptionFilePattern #8 
_rlnJobOptionDirectoryDefault #9 
_rlnJobOptionHelpText #10 
_rlnJobOptionMenuOptions #11 
ctf_intact_first_peak Ignore__CTFs__until__first__peak?            5         No     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__then__CTF-amplitude__correction__will__only__be__performed__from__the__first__peak__of__each__CTF__onward.__This__can__be__useful__if__the__CTF__model__is__inadequate__at__the__lowest__resolution.__Still,__in__general__using__higher__amplitude__contrast__on__the__CTFs__(e.g.__10-20%)__often__yields__better__results.__Therefore,__this__option__is__not__generally__recommended:__try__increasing__amplitude__contrast__(in__your__input__STAR__file)__first! ++undefined++ 
do_combine_thru_disc Combine__iterations__through__disc?            5         No     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__at__the__end__of__every__iteration__all__MPI__slaves__will__write__out__a__large__file__with__their__accumulated__results.__The__MPI__master__will__read__in__all__these__files,__combine__them__all,__and__write__out__a__new__file__with__the__combined__results.__All__MPI__salves__will__then__read__in__the__combined__results.__This__reduces__heavy__load__on__the__network,__but__increases__load__on__the__disc__I/O.__This__will__affect__the__time__it__takes__between__the__progress-bar__in__the__expectation__step__reaching__its__end__(the__mouse__gets__to__the__cheese)__and__the__start__of__the__ensuing__maximisation__step.__It__will__depend__on__your__system__setup__which__is__most__efficient. ++undefined++ 
do_ctf_correction Do__CTF-correction?            5        Yes     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__CTFs__will__be__corrected__inside__the__MAP__refinement.__The__resulting__algorithm__intrinsically__implements__the__optimal__linear,__or__Wiener__filter.__Note__that__CTF__parameters__for__all__images__need__to__be__given__in__the__input__STAR__file.__The__command__'relion_refine__--print_metadata_labels'__will__print__a__list__of__all__possible__metadata__labels__for__that__STAR__file.__See__the__RELION__Wiki__for__more__details.&&__Also__make__sure__that__the__correct__pixel__size__(in__Angstrom)__is__given__above!) ++undefined++ 
   do_pad1 Skip__padding?            5         No     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__the__calculations__will__not__use__padding__in__Fourier__space__for__better__interpolation__in__the__references.__Otherwise,__references__are__padded__2x__before__Fourier__transforms__are__calculated.__Skipping__padding__(i.e.__use__--pad__1)__gives__nearly__as__good__results__as__using__--pad__2,__but__some__artifacts__may__appear__in__the__corners__from__signal__that__is__folded__back. ++undefined++ 
do_parallel_discio Use__parallel__disc__I/O?            5        Yes     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__all__MPI__slaves__will__read__their__own__images__from__disc.__Otherwise,__only__the__master__will__read__images__and__send__them__through__the__network__to__the__slaves.__Parallel__file__systems__like__gluster__of__fhgfs__are__good__at__parallel__disc__I/O.__NFS__may__break__with__many__slaves__reading__in__parallel. ++undefined++ 
do_preread_images Pre-read__all__particles__into__RAM?            5         No     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__all__particle__images__will__be__read__into__computer__memory,__which__will__greatly__speed__up__calculations__on__systems__with__slow__disk__access.__However,__one__should__of__course__be__careful__with__the__amount__of__RAM__available.__Because__particles__are__read__in__float-precision,__it__will__take__(__N__*__box_size__*__box_size__*__4__/__(1024__*__1024__*__1024)__)__Giga-bytes__to__read__N__particles__into__RAM.__For__100__thousand__200x200__images,__that__becomes__15Gb,__or__60__Gb__for__the__same__number__of__400x400__particles.__Remember__that__running__a__single__MPI__slave__on__each__node__that__runs__as__many__threads__as__available__cores__will__have__access__to__all__available__RAM.__&&&&If__parallel__disc__I/O__is__set__to__No,__then__only__the__master__reads__all__particles__into__RAM__and__sends__those__particles__through__the__network__to__the__MPI__slaves__during__the__refinement__iterations. ++undefined++ 
  do_queue Submit__to__queue?            5         No     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__the__job__will__be__submit__to__a__queue,__otherwise__the__job__will__be__executed__locally.__Note__that__only__MPI__jobs__may__be__sent__to__a__queue.__The__default__can__be__set__through__the__environment__variable__RELION_QUEUE_USE. ++undefined++ 
do_solvent Flatten__and__enforce__non-negative__solvent?            5        Yes     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__the__job__will__apply__a__spherical__mask__and__enforce__all__values__in__the__reference__to__be__non-negative. ++undefined++ 
   fn_cont Continue__from__here:__            2         ""     0.000000     0.000000     0.000000 STAR__Files__(*_optimiser.star) CURRENT_ODIR Select__the__*_optimiser.star__file__for__the__iteration__from__which__you__want__to__continue__a__previous__run.__Note__that__the__Output__rootname__of__the__continued__run__and__the__rootname__of__the__previous__run__cannot__be__the__same.__If__they__are__the__same,__the__program__will__automatically__add__a__'_ctX'__to__the__output__rootname,__with__X__being__the__iteration__from__which__one__continues__the__previous__run. ++undefined++ 
    fn_img Input__images__STAR__file:            3         ""     0.000000     0.000000     0.000000 STAR__files__(*.star)__	__Image__stacks__(not__recommended,__read__help!)__(*.{spi,mrcs})  undefined A__STAR__file__with__all__images__(and__their__metadata).__In__SGD,__it__is__very__important__that__there__are__particles__from__enough__different__orientations.__One__only__needs__a__few__thousand__to__10k__particles.__When__selecting__good__2D__classes__in__the__Subset__Selection__jobtype,__use__the__option__to__select__a__maximum__number__of__particles__from__each__class__to__generate__more__even__angular__distributions__for__SGD.&&&&Alternatively,__you__may__give__a__Spider/MRC__stack__of__2D__images,__but__in__that__case__NO__metadata__can__be__included__and__thus__NO__CTF__correction__can__be__performed,__nor__will__it__be__possible__to__perform__noise__spectra__estimation__or__intensity__scale__corrections__in__image__groups.__Therefore,__running__RELION__with__an__input__stack__will__in__general__provide__sub-optimal__results__and__is__therefore__not__recommended!!__Use__the__Preprocessing__procedure__to__get__the__input__STAR__file__in__a__semi-automated__manner.__Read__the__RELION__wiki__for__more__information. ++undefined++ 
   gpu_ids Which__GPUs__to__use:            1         ""     0.000000     0.000000     0.000000  undefined  undefined This__argument__is__not__necessary.__If__left__empty,__the__job__itself__will__try__to__allocate__available__GPU__resources.__You__can__override__the__default__allocation__by__providing__a__list__of__which__GPUs__(0,1,2,3,__etc)__to__use.__MPI-processes__are__separated__by__':',__threads__by__','.__For__example:__'0,0:1,1:0,0:1,1' ++undefined++ 
min_dedicated Minimum__dedicated__cores__per__node:            6         24     1.000000    64.000000     1.000000  undefined  undefined Minimum__number__of__dedicated__cores__that__need__to__be__requested__on__each__node.__This__is__useful__to__force__the__queue__to__fill__up__entire__nodes__of__a__given__size.__The__default__can__be__set__through__the__environment__variable__RELION_MINIMUM_DEDICATED. ++undefined++ 
nr_classes Number__of__classes:            6          1     1.000000    50.000000     1.000000  undefined  undefined The__number__of__classes__(K)__for__a__multi-reference__ab__initio__SGD__refinement.__These__classes__will__be__made__in__an__unsupervised__manner,__starting__from__a__single__reference__in__the__initial__iterations__of__the__SGD,__and__the__references__will__become__increasingly__dissimilar__during__the__inbetween__iterations. ++undefined++ 
    nr_mpi Number__of__MPI__procs:            6          1     1.000000    64.000000     1.000000  undefined  undefined Number__of__MPI__nodes__to__use__in__parallel.__When__set__to__1,__MPI__will__not__be__used.__The__maximum__can__be__set__through__the__environment__variable__RELION_MPI_MAX. ++undefined++ 
   nr_pool Number__of__pooled__particles:            6          3     1.000000    16.000000     1.000000  undefined  undefined Particles__are__processed__in__individual__batches__by__MPI__slaves.__During__each__batch,__a__stack__of__particle__images__is__only__opened__and__closed__once__to__improve__disk__access__times.__All__particle__images__of__a__single__batch__are__read__into__memory__together.__The__size__of__these__batches__is__at__least__one__particle__per__thread__used.__The__nr_pooled_particles__parameter__controls__how__many__particles__are__read__together__for__each__thread.__If__it__is__set__to__3__and__one__uses__8__threads,__batches__of__3x8=24__particles__will__be__read__together.__This__may__improve__performance__on__systems__where__disk__access,__and__particularly__metadata__handling__of__disk__access,__is__a__problem.__It__has__a__modest__cost__of__increased__RAM__usage. ++undefined++ 
nr_threads Number__of__threads:            6          1     1.000000    16.000000     1.000000  undefined  undefined Number__of__shared-memory__(POSIX)__threads__to__use__in__parallel.__When__set__to__1,__no__multi-threading__will__be__used.__The__maximum__can__be__set__through__the__environment__variable__RELION_THREAD_MAX. ++undefined++ 
offset_range Offset__search__range__(pix):            6          6     0.000000    30.000000     1.000000  undefined  undefined Probabilities__will__be__calculated__only__for__translations__in__a__circle__with__this__radius__(in__pixels).__The__center__of__this__circle__changes__at__every__iteration__and__is__placed__at__the__optimal__translation__for__each__image__in__the__previous__iteration.&& ++undefined++ 
offset_step Offset__search__step__(pix):            6          2     0.100000     5.000000     0.100000  undefined  undefined Translations__will__be__sampled__with__this__step-size__(in__pixels).Translational__sampling__is__also__done__using__the__adaptive__approach.__Therefore,__if__adaptive=1,__the__translations__will__first__be__evaluated__on__a__2x__coarser__grid.&&__ ++undefined++ 
other_args Additional__arguments:            1         ""     0.000000     0.000000     0.000000  undefined  undefined In__this__box__command-line__arguments__may__be__provided__that__are__not__generated__by__the__GUI.__This__may__be__useful__for__testing__developmental__options__and/or__expert__use__of__the__program.__To__print__a__list__of__possible__options,__run__the__corresponding__program__from__the__command__line__without__any__arguments. ++undefined++ 
particle_diameter Mask__diameter__(A):            6        200     0.000000  1000.000000    10.000000  undefined  undefined The__experimental__images__will__be__masked__with__a__soft__circular__mask__with__this__diameter.__Make__sure__this__radius__is__not__set__too__small__because__that__may__mask__away__part__of__the__signal!__If__set__to__a__value__larger__than__the__image__size__no__masking__will__be__performed.&&The__same__diameter__will__also__be__used__for__a__spherical__mask__of__the__reference__structures__if__no__user-provided__mask__is__specified. ++undefined++ 
      qsub Queue__submit__command:            1       qsub     0.000000     0.000000     0.000000  undefined  undefined Name__of__the__command__used__to__submit__scripts__to__the__queue,__e.g.__qsub__or__bsub.&&Note__that__the__person__who__installed__RELION__should__have__made__a__custom__script__for__your__cluster/queue__setup.__Check__this__is__the__case__(or__create__your__own__script__following__the__RELION__Wiki)__if__you__have__trouble__submitting__jobs.__The__default__command__can__be__set__through__the__environment__variable__RELION_QSUB_COMMAND. ++undefined++ 
qsubscript Standard__submission__script:            2 /public/EM/RELION/relion/bin/relion_qsub.csh     0.000000     0.000000     0.000000 Script__Files__(*.{csh,sh,bash,script})          . The__template__for__your__standard__queue__job__submission__script.__Its__default__location__may__be__changed__by__setting__the__environment__variable__RELION_QSUB_TEMPLATE.__In__the__template__script__a__number__of__variables__will__be__replaced:__&&XXXcommandXXX__=__relion__command__+__arguments;__&&XXXqueueXXX__=__The__queue__name;__&&XXXmpinodesXXX__=__The__number__of__MPI__nodes;__&&XXXthreadsXXX__=__The__number__of__threads;__&&XXXcoresXXX__=__XXXmpinodesXXX__*__XXXthreadsXXX;__&&XXXdedicatedXXX__=__The__minimum__number__of__dedicated__cores__on__each__node;__&&XXXnodesXXX__=__The__number__of__requested__nodes__=__CEIL(XXXcoresXXX__/__XXXdedicatedXXX);__&&If__these__options__are__not__enough__for__your__standard__jobs,__you__may__define__a__user-specified__number__of__extra__variables:__XXXextra1XXX,__XXXextra2XXX,__etc.__The__number__of__extra__variables__is__controlled__through__the__environment__variable__RELION_QSUB_EXTRA_COUNT.__Their__help__text__is__set__by__the__environment__variables__RELION_QSUB_EXTRA1,__RELION_QSUB_EXTRA2,__etc__For__example,__setenv__RELION_QSUB_EXTRA_COUNT__1,__together__with__setenv__RELION_QSUB_EXTRA1__"Max__number__of__hours__in__queue"__will__result__in__an__additional__(text)__ein__the__GUI__Any__variables__XXXextra1XXX__in__the__template__script__will__be__replaced__by__the__corresponding__value.Likewise,__default__values__for__the__extra__entries__can__be__set__through__environment__variables__RELION_QSUB_EXTRA1_DEFAULT,__RELION_QSUB_EXTRA2_DEFAULT,__etc.__But__note__that__(unlike__all__other__entries__in__the__GUI)__the__extra__values__are__not__remembered__from__one__run__to__the__other. ++undefined++ 
 queuename Queue__name:__            1    openmpi     0.000000     0.000000     0.000000  undefined  undefined Name__of__the__queue__to__which__to__submit__the__job.__The__default__name__can__be__set__through__the__environment__variable__RELION_QUEUE_NAME. ++undefined++ 
  sampling Initial__angular__sampling:            4 15__degrees     0.000000     0.000000     0.000000  undefined  undefined There__are__only__a__few__discrete__angular__samplings__possible__because__we__use__the__HealPix__library__to__generate__the__sampling__of__the__first__two__Euler__angles__on__the__sphere.__The__samplings__are__approximate__numbers__and__vary__slightly__over__the__sphere.&&__For__initial__model__generation__at__low__resolutions,__coarser__angular__samplings__can__often__be__used__than__in__normal__3D__classifications/refinements,__e.g.__15__degrees.__During__the__inbetween__and__final__SGD__iterations,__the__sampling__will__be__adjusted__to__the__resolution,__given__the__particle__size. ++30__degrees++15__degrees++7.5__degrees++3.7__degrees++1.8__degrees++0.9__degrees++0.5__degrees++0.2__degrees++0.1__degrees++ 
scratch_dir Copy__particles__to__scratch__directory:            1         ""     0.000000     0.000000     0.000000  undefined  undefined If__a__directory__is__provided__here,__then__the__job__will__create__a__sub-directory__in__it__called__relion_volatile.__If__that__relion_volatile__directory__already__exists,__it__will__be__wiped.__Then,__the__program__will__copy__all__input__particles__into__a__large__stack__inside__the__relion_volatile__subdirectory.__Provided__this__directory__is__on__a__fast__local__drive__(e.g.__an__SSD__drive),__processing__in__all__the__iterations__will__be__faster.__If__the__job__finishes__correctly,__the__relion_volatile__directory__will__be__wiped.__If__the__job__crashes,__you__may__want__to__remove__it__yourself. ++undefined++ 
sgd_fin_iter Number__of__final__iterations:            6         50    10.000000   300.000000    10.000000  undefined  undefined Number__of__final__SGD__iterations,__at__which__the__final__resolution__cutoff__and__the__final__subset__size__will__be__used,__and__multiple__references__are__left__dissimilar.__50__seems__to__work__well__in__many__cases.__Perhaps__increase__when__multiple__reference__have__trouble__separating. ++undefined++ 
sgd_fin_resol Final__resolution__(A):            6         15     5.000000    30.000000     5.000000  undefined  undefined This__is__the__resolution__cutoff__(in__A)__that__will__be__applied__during__the__final__SGD__iterations.__15A__seems__to__work__well__in__many__cases. ++undefined++ 
sgd_fin_subset_size Final__mini-batch__size:            6        500   100.000000  2000.000000   100.000000  undefined  undefined The__number__of__particles__that__will__be__processed__during__the__final__iterations.__300-500__seems__to__work__well__in__many__cases.__Higher__values__may__result__in__increased__resolutions,__but__at__increased__computational__costs__and__possibly__reduced__searches__of__the__energy__landscape,__but__possibly__at__reduced__resolutions. ++undefined++ 
sgd_inbetween_iter Number__of__in-between__iterations:            6        200    50.000000   500.000000    50.000000  undefined  undefined Number__of__SGD__iterations__between__the__initial__and__final__ones.__During__these__in-between__iterations,__the__resolution__is__linearly__increased,__together__with__the__mini-batch__or__subset__size.__In__case__of__a__multi-class__refinement,__the__different__references__are__also__increasingly__left__to__become__dissimilar.__200__seems__to__work__well__in__many__cases.__Increase__if__multiple__references__have__trouble__separating,__or__the__correct__solution__is__not__found. ++undefined++ 
sgd_ini_iter Number__of__initial__iterations:            6         50    10.000000   300.000000    10.000000  undefined  undefined Number__of__initial__SGD__iterations,__at__which__the__initial__resolution__cutoff__and__the__initial__subset__size__will__be__used,__and__multiple__references__are__kept__the__same.__50__seems__to__work__well__in__many__cases.__Increase__if__the__correct__solution__is__not__found. ++undefined++ 
sgd_ini_resol Initial__resolution__(A):            6         35    10.000000    60.000000     5.000000  undefined  undefined This__is__the__resolution__cutoff__(in__A)__that__will__be__applied__during__the__initial__SGD__iterations.__35A__seems__to__work__well__in__many__cases. ++undefined++ 
sgd_ini_subset_size Initial__mini-batch__size:            6        100    30.000000   300.000000    10.000000  undefined  undefined The__number__of__particles__that__will__be__processed__during__the__initial__iterations.__100__seems__to__work__well__in__many__cases.__Lower__values__may__result__in__wider__searches__of__the__energy__landscape,__but__possibly__at__reduced__resolutions. ++undefined++ 
sgd_sigma2fudge_halflife Increased__noise__variance__half-life:            6         -1   -100.00000 10000.000000   100.000000  undefined  undefined When__set__to__a__positive__value,__the__initial__estimates__of__the__noise__variance__will__internally__be__multiplied__by__8,__and__then__be__gradually__reduced,__having__50%__after__this__many__particles__have__been__processed.__By__default,__this__option__is__switched__off__by__setting__this__value__to__a__negative__number.__In__some__difficult__cases,__switching__this__option__on__helps.__In__such__cases,__values__around__1000__have__been__found__to__be__useful.__Change__the__factor__of__eight__with__the__additional__argument__--sgd_sigma2fudge_ini ++undefined++ 
sgd_write_iter Write-out__frequency__(iter):            6         10     1.000000    50.000000     1.000000  undefined  undefined Every__how__many__iterations__do__you__want__to__write__the__model__to__disk? ++undefined++ 
  sym_name  Symmetry:            1         C1     0.000000     0.000000     0.000000  undefined  undefined SGD__sometimes__works__better__in__C1.__If__you__make__an__initial__model__in__C1__but__want__to__run__Class3D/Refine3D__with__a__higher__point__group__symmetry,__the__reference__model__must__be__rotated__to__conform__the__symmetry__convention.__You__can__do__this__by__the__relion_align_symmetry__command. ++undefined++ 
   use_gpu Use__GPU__acceleration?            5         No     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__the__job__will__try__to__use__GPU__acceleration. ++undefined++ 
 
