job_type == 4
is_continue == false
Pixel size in micrographs (A) == -1
Pixel size in references (A) == 3.54
Pick amyloid segments? == No
Are References CTF corrected? == Yes
Ignore CTFs until first peak? == No
References have inverted contrast? == Yes
OR: use Laplacian-of-Gaussian? == No
Pick 2D helical segments? == No
Submit to queue? == No
Read FOM maps? == No
OR: provide a 3D reference? == No
Write FOM maps? == No
Input micrographs for autopick: == CtfFind/job003/micrographs_ctf.star
3D reference: == 
2D references: == Select/job009/class_averages.star
Which GPUs to use: == 0:1:2:3
Number of unique asymmetrical units: == 1
Helical rise (A): == -1
Maximum curvature (kappa):  == 0.1
Minimum length (A):  == -1
Tube diameter (A):  == 200
Highpass filter (A) == -1
Adjust default threshold (stddev): == 0
Max. diameter for LoG filter (A) == 180
Min. diameter for LoG filter (A) == 150
Are the particles white? == No
Maximum resolution to consider (A) == 20
Upper threshold (stddev): == 5
Lowpass filter references (A) == 20
Maximum stddev noise: == -1
Minimum dedicated cores per node: == 24
Minimum avg noise: == -999
Minimum inter-particle distance (A): == 100
Number of MPI procs: == 4
Additional arguments: == 
Mask diameter (A) == -1
In-plane angular sampling (deg) == 5
Queue submit command: == qsub
Standard submission script: == /public/EM/RELION/relion/bin/relion_qsub.csh
Queue name:  == openmpi
3D angular sampling: == 30 degrees
Symmetry: == C1
Shrink factor: == 0
Picking threshold: == 0
Use GPU acceleration? == Yes
