
# version 30001

data_job

_rlnJobType                            10
_rlnJobIsContinue                       0
 

# version 30001

data_joboptions_values

loop_ 
_rlnJobOptionVariable #1 
_rlnJobOptionValue #2 
auto_local_sampling 1.8__degrees 
ctf_corrected_ref        Yes 
ctf_intact_first_peak         No 
do_apply_helical_symmetry        Yes 
do_combine_thru_disc         No 
do_ctf_correction        Yes 
  do_helix         No 
do_local_search_helical_symmetry         No 
   do_pad1         No 
do_parallel_discio        Yes 
do_preread_images        Yes 
  do_queue         No 
do_solvent_fsc        Yes 
do_zero_mask        Yes 
   fn_cont         "" 
    fn_img Polish/job028/shiny.star 
   fn_mask MaskCreate/job020/mask.mrc 
    fn_ref Refine3D/job025/run_class001.mrc 
   gpu_ids    0:1:2:3 
helical_nr_asu          1 
helical_range_distance         -1 
helical_rise_inistep          0 
helical_rise_initial          0 
helical_rise_max          0 
helical_rise_min          0 
helical_tube_inner_diameter         -1 
helical_tube_outer_diameter         -1 
helical_twist_inistep          0 
helical_twist_initial          0 
helical_twist_max          0 
helical_twist_min          0 
helical_z_percentage         30 
  ini_high         50 
keep_tilt_prior_fixed        Yes 
min_dedicated         24 
    nr_mpi          5 
   nr_pool         30 
nr_threads          6 
offset_range          5 
offset_step          1 
other_args         "" 
particle_diameter        200 
      qsub       qsub 
qsubscript /public/EM/RELION/relion/bin/relion_qsub.csh 
 queuename    openmpi 
 range_psi         10 
 range_rot         -1 
range_tilt         15 
ref_correct_greyscale        Yes 
  sampling 7.5__degrees 
scratch_dir         "" 
  sym_name         D2 
   use_gpu        Yes 
 

# version 30001

data_joboptions_full_definition

loop_ 
_rlnJobOptionVariable #1 
_rlnJobOptionGUILabel #2 
_rlnJoboptionType #3 
_rlnJobOptionDefaultValue #4 
_rlnJobOptionSliderMin #5 
_rlnJobOptionSliderMax #6 
_rlnJobOptionSliderStep #7 
_rlnJobOptionFilePattern #8 
_rlnJobOptionDirectoryDefault #9 
_rlnJobOptionHelpText #10 
_rlnJobOptionMenuOptions #11 
auto_local_sampling Local__searches__from__auto-sampling:            4 1.8__degrees     0.000000     0.000000     0.000000  undefined  undefined In__the__automated__procedure__to__increase__the__angular__samplings,__local__angular__searches__of__-6/+6__times__the__sampling__rate__will__be__used__from__this__angular__sampling__rate__onwards.__For__most__lower-symmetric__particles__a__value__of__1.8__degrees__will__be__sufficient.__Perhaps__icosahedral__symmetries__may__benefit__from__a__smaller__value__such__as__0.9__degrees. ++30__degrees++15__degrees++7.5__degrees++3.7__degrees++1.8__degrees++0.9__degrees++0.5__degrees++0.2__degrees++0.1__degrees++ 
ctf_corrected_ref Has__reference__been__CTF-corrected?            5         No     0.000000     0.000000     0.000000  undefined  undefined Set__this__option__to__Yes__if__the__reference__map__represents__density__that__is__unaffected__by__CTF__phases__and__amplitudes,__e.g.__it__was__created__using__CTF__correction__(Wiener__filtering)__inside__RELION__or__from__a__PDB.__&&If__set__to__No,__then__in__the__first__iteration,__the__Fourier__transforms__of__the__reference__projections__are__not__multiplied__by__the__CTFs. ++undefined++ 
ctf_intact_first_peak Ignore__CTFs__until__first__peak?            5         No     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__then__CTF-amplitude__correction__will__only__be__performed__from__the__first__peak__of__each__CTF__onward.__This__can__be__useful__if__the__CTF__model__is__inadequate__at__the__lowest__resolution.__Still,__in__general__using__higher__amplitude__contrast__on__the__CTFs__(e.g.__10-20%)__often__yields__better__results.__Therefore,__this__option__is__not__generally__recommended:__try__increasing__amplitude__contrast__(in__your__input__STAR__file)__first! ++undefined++ 
do_apply_helical_symmetry Apply__helical__symmetry?            5        Yes     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__helical__symmetry__will__be__applied__in__every__iteration.__Set__to__No__if__you__have__just__started__a__project,__helical__symmetry__is__unknown__or__not__yet__estimated. ++undefined++ 
do_combine_thru_disc Combine__iterations__through__disc?            5         No     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__at__the__end__of__every__iteration__all__MPI__slaves__will__write__out__a__large__file__with__their__accumulated__results.__The__MPI__master__will__read__in__all__these__files,__combine__them__all,__and__write__out__a__new__file__with__the__combined__results.__All__MPI__salves__will__then__read__in__the__combined__results.__This__reduces__heavy__load__on__the__network,__but__increases__load__on__the__disc__I/O.__This__will__affect__the__time__it__takes__between__the__progress-bar__in__the__expectation__step__reaching__its__end__(the__mouse__gets__to__the__cheese)__and__the__start__of__the__ensuing__maximisation__step.__It__will__depend__on__your__system__setup__which__is__most__efficient. ++undefined++ 
do_ctf_correction Do__CTF-correction?            5        Yes     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__CTFs__will__be__applied__to__the__projections__of__the__map.__This__requires__that__CTF__information__is__present__in__the__input__STAR__file. ++undefined++ 
  do_helix Do__helical__reconstruction?            5         No     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__then__perform__3D__helical__reconstruction. ++undefined++ 
do_local_search_helical_symmetry Do__local__searches__of__symmetry?            5         No     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__then__perform__local__searches__of__helical__twist__and__rise__within__given__ranges. ++undefined++ 
   do_pad1 Skip__padding?            5         No     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__the__calculations__will__not__use__padding__in__Fourier__space__for__better__interpolation__in__the__references.__Otherwise,__references__are__padded__2x__before__Fourier__transforms__are__calculated.__Skipping__padding__(i.e.__use__--pad__1)__gives__nearly__as__good__results__as__using__--pad__2,__but__some__artifacts__may__appear__in__the__corners__from__signal__that__is__folded__back. ++undefined++ 
do_parallel_discio Use__parallel__disc__I/O?            5        Yes     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__all__MPI__slaves__will__read__their__own__images__from__disc.__Otherwise,__only__the__master__will__read__images__and__send__them__through__the__network__to__the__slaves.__Parallel__file__systems__like__gluster__of__fhgfs__are__good__at__parallel__disc__I/O.__NFS__may__break__with__many__slaves__reading__in__parallel. ++undefined++ 
do_preread_images Pre-read__all__particles__into__RAM?            5         No     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__all__particle__images__will__be__read__into__computer__memory,__which__will__greatly__speed__up__calculations__on__systems__with__slow__disk__access.__However,__one__should__of__course__be__careful__with__the__amount__of__RAM__available.__Because__particles__are__read__in__float-precision,__it__will__take__(__N__*__box_size__*__box_size__*__8__/__(1024__*__1024__*__1024)__)__Giga-bytes__to__read__N__particles__into__RAM.__For__100__thousand__200x200__images,__that__becomes__15Gb,__or__60__Gb__for__the__same__number__of__400x400__particles.__Remember__that__running__a__single__MPI__slave__on__each__node__that__runs__as__many__threads__as__available__cores__will__have__access__to__all__available__RAM.__&&&&If__parallel__disc__I/O__is__set__to__No,__then__only__the__master__reads__all__particles__into__RAM__and__sends__those__particles__through__the__network__to__the__MPI__slaves__during__the__refinement__iterations. ++undefined++ 
  do_queue Submit__to__queue?            5         No     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__the__job__will__be__submit__to__a__queue,__otherwise__the__job__will__be__executed__locally.__Note__that__only__MPI__jobs__may__be__sent__to__a__queue.__The__default__can__be__set__through__the__environment__variable__RELION_QUEUE_USE. ++undefined++ 
do_solvent_fsc Use__solvent-flattened__FSCs?            5         No     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__then__instead__of__using__unmasked__maps__to__calculate__the__gold-standard__FSCs__during__refinement,__masked__half-maps__are__used__and__a__post-processing-like__correction__of__the__FSC__curves__(with__phase-randomisation)__is__performed__every__iteration.__This__only__works__when__a__reference__mask__is__provided__on__the__I/O__tab.__This__may__yield__higher-resolution__maps,__especially__when__the__mask__contains__only__a__relatively__small__volume__inside__the__box. ++undefined++ 
do_zero_mask Mask__individual__particles__with__zeros?            5        Yes     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__then__in__the__individual__particles,__the__area__outside__a__circle__with__the__radius__of__the__particle__will__be__set__to__zeros__prior__to__taking__the__Fourier__transform.__This__will__remove__noise__and__therefore__increase__sensitivity__in__the__alignment__and__classification.__However,__it__will__also__introduce__correlations__between__the__Fourier__components__that__are__not__modelled.__When__set__to__No,__then__the__solvent__area__is__filled__with__random__noise,__which__prevents__introducing__correlations.High-resolution__refinements__(e.g.__ribosomes__or__other__large__complexes__in__3D__auto-refine)__tend__to__work__better__when__filling__the__solvent__area__with__random__noise__(i.e.__setting__this__option__to__No),__refinements__of__smaller__complexes__and__most__classifications__go__better__when__using__zeros__(i.e.__setting__this__option__to__Yes). ++undefined++ 
   fn_cont Continue__from__here:__            2         ""     0.000000     0.000000     0.000000 STAR__Files__(*_optimiser.star) CURRENT_ODIR Select__the__*_optimiser.star__file__for__the__iteration__from__which__you__want__to__continue__a__previous__run.__Note__that__the__Output__rootname__of__the__continued__run__and__the__rootname__of__the__previous__run__cannot__be__the__same.__If__they__are__the__same,__the__program__will__automatically__add__a__'_ctX'__to__the__output__rootname,__with__X__being__the__iteration__from__which__one__continues__the__previous__run. ++undefined++ 
    fn_img Input__images__STAR__file:            3         ""     0.000000     0.000000     0.000000 STAR__files__(*.star)__	__Image__stacks__(not__recommended,__read__help!)__(*.{spi,mrcs})  undefined A__STAR__file__with__all__images__(and__their__metadata).__&&&&Alternatively,__you__may__give__a__Spider/MRC__stack__of__2D__images,__but__in__that__case__NO__metadata__can__be__included__and__thus__NO__CTF__correction__can__be__performed,__nor__will__it__be__possible__to__perform__noise__spectra__estimation__or__intensity__scale__corrections__in__image__groups.__Therefore,__running__RELION__with__an__input__stack__will__in__general__provide__sub-optimal__results__and__is__therefore__not__recommended!!__Use__the__Preprocessing__procedure__to__get__the__input__STAR__file__in__a__semi-automated__manner.__Read__the__RELION__wiki__for__more__information. ++undefined++ 
   fn_mask Reference__mask__(optional):            3         ""     0.000000     0.000000     0.000000 Image__Files__(*.{spi,vol,msk,mrc})  undefined If__no__mask__is__provided,__a__soft__spherical__mask__based__on__the__particle__diameter__will__be__used.&&Otherwise,__provide__a__Spider/mrc__map__containing__a__(soft)__mask__with__the__same__dimensions__as__the__reference(s),__and__values__between__0__and__1,__with__1__being__100%__protein__and__0__being__100%__solvent.__The__reconstructed__reference__map__will__be__multiplied__by__this__mask.&&In__some__cases,__for__example__for__non-empty__icosahedral__viruses,__it__is__also__useful__to__use__a__second__mask.__For__all__white__(value__1)__pixels__in__this__second__mask__the__corresponding__pixels__in__the__reconstructed__map__are__set__to__the__average__value__of__these__pixels.__Thereby,__for__example,__the__higher__density__inside__the__virion__may__be__set__to__a__constant.__Note__that__this__second__mask__should__have__one-values__inside__the__virion__and__zero-values__in__the__capsid__and__the__solvent__areas.__To__use__a__second__mask,__use__the__additional__option__--solvent_mask2,__which__may__given__in__the__Additional__arguments__line__(in__the__Running__tab). ++undefined++ 
    fn_ref Reference__map:            3         ""     0.000000     0.000000     0.000000 Image__Files__(*.{spi,vol,mrc})  undefined A__3D__map__in__MRC/Spider__format.__	Make__sure__this__map__has__the__same__dimensions__and__the__same__pixel__size__as__your__input__images. ++undefined++ 
   gpu_ids Which__GPUs__to__use:            1         ""     0.000000     0.000000     0.000000  undefined  undefined This__argument__is__not__necessary.__If__left__empty,__the__job__itself__will__try__to__allocate__available__GPU__resources.__You__can__override__the__default__allocation__by__providing__a__list__of__which__GPUs__(0,1,2,3,__etc)__to__use.__MPI-processes__are__separated__by__':',__threads__by__','.____For__example:__'0,0:1,1:0,0:1,1' ++undefined++ 
helical_nr_asu Number__of__unique__asymmetrical__units:            6          1     1.000000   100.000000     1.000000  undefined  undefined Number__of__unique__helical__asymmetrical__units__in__each__segment__box.__If__the__inter-box__distance__(set__in__segment__picking__step)__is__100__Angstroms__and__the__estimated__helical__rise__is__~20__Angstroms,__then__set__this__value__to__100__/__20__=__5__(nearest__integer).__This__integer__should__not__be__less__than__1.__The__correct__value__is__essential__in__measuring__the__signal__to__noise__ratio__in__helical__reconstruction. ++undefined++ 
helical_range_distance Range__factor__of__local__averaging:            6         -1     1.000000     5.000000     0.100000  undefined  undefined Local__averaging__of__orientations__and__translations__will__be__performed__within__a__range__of__+/-__this__value__*__the__box__size.__Polarities__are__also__set__to__be__the__same__for__segments__coming__from__the__same__tube__during__local__refinement.__Values__of__~__2.0__are__recommended__for__flexible__structures__such__as__MAVS-CARD__filaments,__ParM,__MamK,__etc.__This__option__might__not__improve__the__reconstructions__of__helices__formed__from__curled__2D__lattices__(TMV__and__VipA/VipB).__Set__to__negative__to__disable__this__option. ++undefined++ 
helical_rise_inistep Helical__rise__search__(A)__-__Step:            1          0     0.000000     0.000000     0.000000  undefined  undefined Minimum,__maximum__and__initial__step__for__helical__rise__search.__Helical__rise__is__a__positive__value__in__Angstroms.__Generally__it__is__not__necessary__for__the__user__to__provide__an__initial__step__(less__than__1%__the__initial__helical__rise,__5~1000__samplings__as__default).__But__it__needs__to__be__set__manually__if__the__default__value__does__not__guarantee__convergence.__The__program__cannot__find__a__reasonable__symmetry__if__the__true__helical__parameters__fall__out__of__the__given__ranges.__Note__that__the__final__reconstruction__can__still__converge__if__wrong__helical__and__point__group__symmetry__are__provided. ++undefined++ 
helical_rise_initial Initial__helical__rise__(A):            1          0     0.000000     0.000000     0.000000  undefined  undefined Initial__helical__symmetry.__Set__helical__twist__(in__degrees)__to__positive__value__if__it__is__a__right-handed__helix.__Helical__rise__is__a__positive__value__in__Angstroms.__If__local__searches__of__helical__symmetry__are__planned,__initial__values__of__helical__twist__and__rise__should__be__within__their__respective__ranges. ++undefined++ 
helical_rise_max Helical__rise__search__(A)__-__Max:            1          0     0.000000     0.000000     0.000000  undefined  undefined Minimum,__maximum__and__initial__step__for__helical__rise__search.__Helical__rise__is__a__positive__value__in__Angstroms.__Generally__it__is__not__necessary__for__the__user__to__provide__an__initial__step__(less__than__1%__the__initial__helical__rise,__5~1000__samplings__as__default).__But__it__needs__to__be__set__manually__if__the__default__value__does__not__guarantee__convergence.__The__program__cannot__find__a__reasonable__symmetry__if__the__true__helical__parameters__fall__out__of__the__given__ranges.__Note__that__the__final__reconstruction__can__still__converge__if__wrong__helical__and__point__group__symmetry__are__provided. ++undefined++ 
helical_rise_min Helical__rise__search__(A)__-__Min:            1          0     0.000000     0.000000     0.000000  undefined  undefined Minimum,__maximum__and__initial__step__for__helical__rise__search.__Helical__rise__is__a__positive__value__in__Angstroms.__Generally__it__is__not__necessary__for__the__user__to__provide__an__initial__step__(less__than__1%__the__initial__helical__rise,__5~1000__samplings__as__default).__But__it__needs__to__be__set__manually__if__the__default__value__does__not__guarantee__convergence.__The__program__cannot__find__a__reasonable__symmetry__if__the__true__helical__parameters__fall__out__of__the__given__ranges.__Note__that__the__final__reconstruction__can__still__converge__if__wrong__helical__and__point__group__symmetry__are__provided. ++undefined++ 
helical_tube_inner_diameter Tube__diameter__-__inner__(A):            1         -1     0.000000     0.000000     0.000000  undefined  undefined Inner__and__outer__diameter__(in__Angstroms)__of__the__reconstructed__helix__spanning__across__Z__axis.__Set__the__inner__diameter__to__negative__value__if__the__helix__is__not__hollow__in__the__center.__The__outer__diameter__should__be__slightly__larger__than__the__actual__width__of__helical__tubes__because__it__also__decides__the__shape__of__2D__particle__mask__for__each__segment.__If__the__psi__priors__of__the__extracted__segments__are__not__accurate__enough__due__to__high__noise__level__or__flexibility__of__the__structure,__then__set__the__outer__diameter__to__a__large__value. ++undefined++ 
helical_tube_outer_diameter Tube__diameter__-__outer__(A):            1         -1     0.000000     0.000000     0.000000  undefined  undefined Inner__and__outer__diameter__(in__Angstroms)__of__the__reconstructed__helix__spanning__across__Z__axis.__Set__the__inner__diameter__to__negative__value__if__the__helix__is__not__hollow__in__the__center.__The__outer__diameter__should__be__slightly__larger__than__the__actual__width__of__helical__tubes__because__it__also__decides__the__shape__of__2D__particle__mask__for__each__segment.__If__the__psi__priors__of__the__extracted__segments__are__not__accurate__enough__due__to__high__noise__level__or__flexibility__of__the__structure,__then__set__the__outer__diameter__to__a__large__value. ++undefined++ 
helical_twist_inistep Helical__twist__search__(deg)__-__Step:            1          0     0.000000     0.000000     0.000000  undefined  undefined Minimum,__maximum__and__initial__step__for__helical__twist__search.__Set__helical__twist__(in__degrees)__to__positive__value__if__it__is__a__right-handed__helix.__Generally__it__is__not__necessary__for__the__user__to__provide__an__initial__step__(less__than__1__degree,__5~1000__samplings__as__default).__But__it__needs__to__be__set__manually__if__the__default__value__does__not__guarantee__convergence.__The__program__cannot__find__a__reasonable__symmetry__if__the__true__helical__parameters__fall__out__of__the__given__ranges.__Note__that__the__final__reconstruction__can__still__converge__if__wrong__helical__and__point__group__symmetry__are__provided. ++undefined++ 
helical_twist_initial Initial__helical__twist__(deg):            1          0     0.000000     0.000000     0.000000  undefined  undefined Initial__helical__symmetry.__Set__helical__twist__(in__degrees)__to__positive__value__if__it__is__a__right-handed__helix.__Helical__rise__is__a__positive__value__in__Angstroms.__If__local__searches__of__helical__symmetry__are__planned,__initial__values__of__helical__twist__and__rise__should__be__within__their__respective__ranges. ++undefined++ 
helical_twist_max Helical__twist__search__(deg)__-__Max:            1          0     0.000000     0.000000     0.000000  undefined  undefined Minimum,__maximum__and__initial__step__for__helical__twist__search.__Set__helical__twist__(in__degrees)__to__positive__value__if__it__is__a__right-handed__helix.__Generally__it__is__not__necessary__for__the__user__to__provide__an__initial__step__(less__than__1__degree,__5~1000__samplings__as__default).__But__it__needs__to__be__set__manually__if__the__default__value__does__not__guarantee__convergence.__The__program__cannot__find__a__reasonable__symmetry__if__the__true__helical__parameters__fall__out__of__the__given__ranges.__Note__that__the__final__reconstruction__can__still__converge__if__wrong__helical__and__point__group__symmetry__are__provided. ++undefined++ 
helical_twist_min Helical__twist__search__(deg)__-__Min:            1          0     0.000000     0.000000     0.000000  undefined  undefined Minimum,__maximum__and__initial__step__for__helical__twist__search.__Set__helical__twist__(in__degrees)__to__positive__value__if__it__is__a__right-handed__helix.__Generally__it__is__not__necessary__for__the__user__to__provide__an__initial__step__(less__than__1__degree,__5~1000__samplings__as__default).__But__it__needs__to__be__set__manually__if__the__default__value__does__not__guarantee__convergence.__The__program__cannot__find__a__reasonable__symmetry__if__the__true__helical__parameters__fall__out__of__the__given__ranges.__Note__that__the__final__reconstruction__can__still__converge__if__wrong__helical__and__point__group__symmetry__are__provided. ++undefined++ 
helical_z_percentage Central__Z__length__(%):            6         30     5.000000    80.000000     1.000000  undefined  undefined Reconstructed__helix__suffers__from__inaccuracies__of__orientation__searches.__The__central__part__of__the__box__contains__more__reliable__information__compared__to__the__top__and__bottom__parts__along__Z__axis,__where__Fourier__artefacts__are__also__present__if__the__number__of__helical__asymmetrical__units__is__larger__than__1.__Therefore,__information__from__the__central__part__of__the__box__is__used__for__searching__and__imposing__helical__symmetry__in__real__space.__Set__this__value__(%)__to__the__central__part__length__along__Z__axis__divided__by__the__box__size.__Values__around__30%__are__commonly__used. ++undefined++ 
  ini_high Initial__low-pass__filter__(A):            6         60     0.000000   200.000000     5.000000  undefined  undefined It__is__recommended__to__strongly__low-pass__filter__your__initial__reference__map.__If__it__has__not__yet__been__low-pass__filtered,__it__may__be__done__internally__using__this__option.__If__set__to__0,__no__low-pass__filter__will__be__applied__to__the__initial__reference(s). ++undefined++ 
keep_tilt_prior_fixed Keep__tilt-prior__fixed:            5        Yes     0.000000     0.000000     0.000000  undefined  undefined If__set__to__yes,__the__tilt__prior__will__not__change__during__the__optimisation.__If__set__to__No,__at__each__iteration__the__tilt__prior__will__move__to__the__optimal__tilt__value__for__that__segment__from__the__previous__iteration. ++undefined++ 
min_dedicated Minimum__dedicated__cores__per__node:            6         24     1.000000    64.000000     1.000000  undefined  undefined Minimum__number__of__dedicated__cores__that__need__to__be__requested__on__each__node.__This__is__useful__to__force__the__queue__to__fill__up__entire__nodes__of__a__given__size.__The__default__can__be__set__through__the__environment__variable__RELION_MINIMUM_DEDICATED. ++undefined++ 
    nr_mpi Number__of__MPI__procs:            6          1     1.000000    64.000000     1.000000  undefined  undefined Number__of__MPI__nodes__to__use__in__parallel.__When__set__to__1,__MPI__will__not__be__used.__The__maximum__can__be__set__through__the__environment__variable__RELION_MPI_MAX. ++undefined++ 
   nr_pool Number__of__pooled__particles:            6          3     1.000000    16.000000     1.000000  undefined  undefined Particles__are__processed__in__individual__batches__by__MPI__slaves.__During__each__batch,__a__stack__of__particle__images__is__only__opened__and__closed__once__to__improve__disk__access__times.__All__particle__images__of__a__single__batch__are__read__into__memory__together.__The__size__of__these__batches__is__at__least__one__particle__per__thread__used.__The__nr_pooled_particles__parameter__controls__how__many__particles__are__read__together__for__each__thread.__If__it__is__set__to__3__and__one__uses__8__threads,__batches__of__3x8=24__particles__will__be__read__together.__This__may__improve__performance__on__systems__where__disk__access,__and__particularly__metadata__handling__of__disk__access,__is__a__problem.__It__has__a__modest__cost__of__increased__RAM__usage. ++undefined++ 
nr_threads Number__of__threads:            6          1     1.000000    16.000000     1.000000  undefined  undefined Number__of__shared-memory__(POSIX)__threads__to__use__in__parallel.__When__set__to__1,__no__multi-threading__will__be__used.__The__maximum__can__be__set__through__the__environment__variable__RELION_THREAD_MAX. ++undefined++ 
offset_range Initial__offset__range__(pix):            6          5     0.000000    30.000000     1.000000  undefined  undefined Probabilities__will__be__calculated__only__for__translations__in__a__circle__with__this__radius__(in__pixels).__The__center__of__this__circle__changes__at__every__iteration__and__is__placed__at__the__optimal__translation__for__each__image__in__the__previous__iteration.&&__Note__that__this__will__only__be__the__value__for__the__first__few__iteration(s):__the__sampling__rate__will__be__increased__automatically__after__that. ++undefined++ 
offset_step Initial__offset__step__(pix):            6          1     0.100000     5.000000     0.100000  undefined  undefined Translations__will__be__sampled__with__this__step-size__(in__pixels).Translational__sampling__is__also__done__using__the__adaptive__approach.__Therefore,__if__adaptive=1,__the__translations__will__first__be__evaluated__on__a__2x__coarser__grid.&&__Note__that__this__will__only__be__the__value__for__the__first__few__iteration(s):__the__sampling__rate__will__be__increased__automatically__after__that. ++undefined++ 
other_args Additional__arguments:            1         ""     0.000000     0.000000     0.000000  undefined  undefined In__this__box__command-line__arguments__may__be__provided__that__are__not__generated__by__the__GUI.__This__may__be__useful__for__testing__developmental__options__and/or__expert__use__of__the__program.__To__print__a__list__of__possible__options,__run__the__corresponding__program__from__the__command__line__without__any__arguments. ++undefined++ 
particle_diameter Mask__diameter__(A):            6        200     0.000000  1000.000000    10.000000  undefined  undefined The__experimental__images__will__be__masked__with__a__soft__circular__mask__with__this__diameter.__Make__sure__this__radius__is__not__set__too__small__because__that__may__mask__away__part__of__the__signal!__If__set__to__a__value__larger__than__the__image__size__no__masking__will__be__performed.&&The__same__diameter__will__also__be__used__for__a__spherical__mask__of__the__reference__structures__if__no__user-provided__mask__is__specified. ++undefined++ 
      qsub Queue__submit__command:            1       qsub     0.000000     0.000000     0.000000  undefined  undefined Name__of__the__command__used__to__submit__scripts__to__the__queue,__e.g.__qsub__or__bsub.&&Note__that__the__person__who__installed__RELION__should__have__made__a__custom__script__for__your__cluster/queue__setup.__Check__this__is__the__case__(or__create__your__own__script__following__the__RELION__Wiki)__if__you__have__trouble__submitting__jobs.__The__default__command__can__be__set__through__the__environment__variable__RELION_QSUB_COMMAND. ++undefined++ 
qsubscript Standard__submission__script:            2 /public/EM/RELION/relion/bin/relion_qsub.csh     0.000000     0.000000     0.000000 Script__Files__(*.{csh,sh,bash,script})          . The__template__for__your__standard__queue__job__submission__script.__Its__default__location__may__be__changed__by__setting__the__environment__variable__RELION_QSUB_TEMPLATE.__In__the__template__script__a__number__of__variables__will__be__replaced:__&&XXXcommandXXX__=__relion__command__+__arguments;__&&XXXqueueXXX__=__The__queue__name;__&&XXXmpinodesXXX__=__The__number__of__MPI__nodes;__&&XXXthreadsXXX__=__The__number__of__threads;__&&XXXcoresXXX__=__XXXmpinodesXXX__*__XXXthreadsXXX;__&&XXXdedicatedXXX__=__The__minimum__number__of__dedicated__cores__on__each__node;__&&XXXnodesXXX__=__The__number__of__requested__nodes__=__CEIL(XXXcoresXXX__/__XXXdedicatedXXX);__&&If__these__options__are__not__enough__for__your__standard__jobs,__you__may__define__a__user-specified__number__of__extra__variables:__XXXextra1XXX,__XXXextra2XXX,__etc.__The__number__of__extra__variables__is__controlled__through__the__environment__variable__RELION_QSUB_EXTRA_COUNT.__Their__help__text__is__set__by__the__environment__variables__RELION_QSUB_EXTRA1,__RELION_QSUB_EXTRA2,__etc__For__example,__setenv__RELION_QSUB_EXTRA_COUNT__1,__together__with__setenv__RELION_QSUB_EXTRA1__"Max__number__of__hours__in__queue"__will__result__in__an__additional__(text)__ein__the__GUI__Any__variables__XXXextra1XXX__in__the__template__script__will__be__replaced__by__the__corresponding__value.Likewise,__default__values__for__the__extra__entries__can__be__set__through__environment__variables__RELION_QSUB_EXTRA1_DEFAULT,__RELION_QSUB_EXTRA2_DEFAULT,__etc.__But__note__that__(unlike__all__other__entries__in__the__GUI)__the__extra__values__are__not__remembered__from__one__run__to__the__other. ++undefined++ 
 queuename Queue__name:__            1    openmpi     0.000000     0.000000     0.000000  undefined  undefined Name__of__the__queue__to__which__to__submit__the__job.__The__default__name__can__be__set__through__the__environment__variable__RELION_QUEUE_NAME. ++undefined++ 
 range_psi Angular__search__range__-__psi__(deg):            1         10     0.000000     0.000000     0.000000  undefined  undefined Local__angular__searches__will__be__performed__within__+/-__the__given__amount__(in__degrees)__from__the__optimal__orientation__in__the__previous__iteration.__A__Gaussian__prior__(also__see__previous__option)__will__be__applied,__so__that__orientations__closer__to__the__optimal__orientation__in__the__previous__iteration__will__get__higher__weights__than__those__further__away.&&These__ranges__will__only__be__applied__to__the__rot,__tilt__and__psi__angles__in__the__first__few__iterations__(global__searches__for__orientations)__in__3D__helical__reconstruction.__Values__of__9__or__15__degrees__are__commonly__used.__Higher__values__are__recommended__for__more__flexible__structures__and__more__memory__and__computation__time__will__be__used.__A__range__of__15__degrees__means__sigma__=__5__degrees.&&These__options__will__be__invalid__if__you__choose__to__perform__local__angular__searches__or__not__to__perform__image__alignment__on__'Sampling'__tab. ++undefined++ 
 range_rot Angular__search__range__-__rot__(deg):            1         -1     0.000000     0.000000     0.000000  undefined  undefined Local__angular__searches__will__be__performed__within__+/-__of__the__given__amount__(in__degrees)__from__the__optimal__orientation__in__the__previous__iteration.__The__default__negative__value__means__that__no__local__searches__will__be__performed.__A__Gaussian__prior__will__be__applied,__so__that__orientations__closer__to__the__optimal__orientation__in__the__previous__iteration__will__get__higher__weights__than__those__further__away.&&These__ranges__will__only__be__applied__to__the__rot,__tilt__and__psi__angles__in__the__first__few__iterations__(global__searches__for__orientations)__in__3D__helical__reconstruction.__Values__of__9__or__15__degrees__are__commonly__used.__Higher__values__are__recommended__for__more__flexible__structures__and__more__memory__and__computation__time__will__be__used.__A__range__of__15__degrees__means__sigma__=__5__degrees.&&These__options__will__be__invalid__if__you__choose__to__perform__local__angular__searches__or__not__to__perform__image__alignment__on__'Sampling'__tab. ++undefined++ 
range_tilt Angular__search__range__-__tilt__(deg):            1         15     0.000000     0.000000     0.000000  undefined  undefined Local__angular__searches__will__be__performed__within__+/-__the__given__amount__(in__degrees)__from__the__optimal__orientation__in__the__previous__iteration.__A__Gaussian__prior__(also__see__previous__option)__will__be__applied,__so__that__orientations__closer__to__the__optimal__orientation__in__the__previous__iteration__will__get__higher__weights__than__those__further__away.&&These__ranges__will__only__be__applied__to__the__rot,__tilt__and__psi__angles__in__the__first__few__iterations__(global__searches__for__orientations)__in__3D__helical__reconstruction.__Values__of__9__or__15__degrees__are__commonly__used.__Higher__values__are__recommended__for__more__flexible__structures__and__more__memory__and__computation__time__will__be__used.__A__range__of__15__degrees__means__sigma__=__5__degrees.&&These__options__will__be__invalid__if__you__choose__to__perform__local__angular__searches__or__not__to__perform__image__alignment__on__'Sampling'__tab. ++undefined++ 
ref_correct_greyscale Ref.__map__is__on__absolute__greyscale?            5         No     0.000000     0.000000     0.000000  undefined  undefined Probabilities__are__calculated__based__on__a__Gaussian__noise__model,__which__contains__a__squared__difference__term__between__the__reference__and__the__experimental__image.__This__has__a__consequence__that__the__reference__needs__to__be__on__the__same__absolute__intensity__grey-scale__as__the__experimental__images.__RELION__and__XMIPP__reconstruct__maps__at__their__absolute__intensity__grey-scale.__Other__packages__may__perform__internal__normalisations__of__the__reference__density,__which__will__result__in__incorrect__grey-scales.__Therefore:__if__the__map__was__reconstructed__in__RELION__or__in__XMIPP,__set__this__option__to__Yes,__otherwise__set__it__to__No.__If__set__to__No,__RELION__will__use__a__(grey-scale__invariant)__cross-correlation__criterion__in__the__first__iteration,__and__prior__to__the__second__iteration__the__map__will__be__filtered__again__using__the__initial__low-pass__filter.__This__procedure__is__relatively__quick__and__typically__does__not__negatively__affect__the__outcome__of__the__subsequent__MAP__refinement.__Therefore,__if__in__doubt__it__is__recommended__to__set__this__option__to__No. ++undefined++ 
  sampling Initial__angular__sampling:            4 7.5__degrees     0.000000     0.000000     0.000000  undefined  undefined There__are__only__a__few__discrete__angular__samplings__possible__because__we__use__the__HealPix__library__to__generate__the__sampling__of__the__first__two__Euler__angles__on__the__sphere.__The__samplings__are__approximate__numbers__and__vary__slightly__over__the__sphere.&&__Note__that__this__will__only__be__the__value__for__the__first__few__iteration(s):__the__sampling__rate__will__be__increased__automatically__after__that. ++30__degrees++15__degrees++7.5__degrees++3.7__degrees++1.8__degrees++0.9__degrees++0.5__degrees++0.2__degrees++0.1__degrees++ 
scratch_dir Copy__particles__to__scratch__directory:            1         ""     0.000000     0.000000     0.000000  undefined  undefined If__a__directory__is__provided__here,__then__the__job__will__create__a__sub-directory__in__it__called__relion_volatile.__If__that__relion_volatile__directory__already__exists,__it__will__be__wiped.__Then,__the__program__will__copy__all__input__particles__into__a__large__stack__inside__the__relion_volatile__subdirectory.__Provided__this__directory__is__on__a__fast__local__drive__(e.g.__an__SSD__drive),__processing__in__all__the__iterations__will__be__faster.__If__the__job__finishes__correctly,__the__relion_volatile__directory__will__be__wiped.__If__the__job__crashes,__you__may__want__to__remove__it__yourself. ++undefined++ 
  sym_name  Symmetry:            1         C1     0.000000     0.000000     0.000000  undefined  undefined If__the__molecule__is__asymmetric,__set__Symmetry__group__to__C1.__Note__their__are__multiple__possibilities__for__icosahedral__symmetry:__&&*__I1:__No-Crowther__222__(standard__in__Heymann,__Chagoyen__&__Belnap,__JSB,__151__(2005)__196–207)__&&*__I2:__Crowther__222__&&*__I3:__52-setting__(as__used__in__SPIDER?)&&*__I4:__A__different__52__setting__&&The__command__'relion_refine__--sym__D2__--print_symmetry_ops'__prints__a__list__of__all__symmetry__operators__for__symmetry__group__D2.__RELION__uses__XMIPP's__libraries__for__symmetry__operations.__Therefore,__look__at__the__XMIPP__Wiki__for__more__details:____http://xmipp.cnb.csic.es/twiki/bin/view/Xmipp/WebHome?topic=Symmetry ++undefined++ 
   use_gpu Use__GPU__acceleration?            5         No     0.000000     0.000000     0.000000  undefined  undefined If__set__to__Yes,__the__job__will__try__to__use__GPU__acceleration. ++undefined++ 
 
