job_type == 10
is_continue == false
Local searches from auto-sampling: == 1.8 degrees
Has reference been CTF-corrected? == Yes
Ignore CTFs until first peak? == No
Apply helical symmetry? == Yes
Combine iterations through disc? == No
Do CTF-correction? == Yes
Do helical reconstruction? == No
Do local searches of symmetry? == No
Skip padding? == No
Use parallel disc I/O? == Yes
Pre-read all particles into RAM? == Yes
Submit to queue? == No
Use solvent-flattened FSCs? == Yes
Mask individual particles with zeros? == Yes
Continue from here:  == 
Input images STAR file: == Polish/job028/shiny.star
Reference mask (optional): == MaskCreate/job020/mask.mrc
Reference map: == Refine3D/job025/run_class001.mrc
Which GPUs to use: == 0:1:2:3
Number of unique asymmetrical units: == 1
Range factor of local averaging: == -1
Helical rise search (A) - Step: == 0
Initial helical rise (A): == 0
Helical rise search (A) - Max: == 0
Helical rise search (A) - Min: == 0
Tube diameter - inner (A): == -1
Tube diameter - outer (A): == -1
Helical twist search (deg) - Step: == 0
Initial helical twist (deg): == 0
Helical twist search (deg) - Max: == 0
Helical twist search (deg) - Min: == 0
Central Z length (%): == 30
Initial low-pass filter (A): == 50
Keep tilt-prior fixed: == Yes
Minimum dedicated cores per node: == 24
Number of MPI procs: == 5
Number of pooled particles: == 30
Number of threads: == 6
Initial offset range (pix): == 5
Initial offset step (pix): == 1
Additional arguments: == 
Mask diameter (A): == 200
Queue submit command: == qsub
Standard submission script: == /public/EM/RELION/relion/bin/relion_qsub.csh
Queue name:  == openmpi
Angular search range - psi (deg): == 10
Angular search range - rot (deg): == -1
Angular search range - tilt (deg): == 15
Ref. map is on absolute greyscale? == Yes
Initial angular sampling: == 7.5 degrees
Copy particles to scratch directory: == 
Symmetry: == D2
Use GPU acceleration? == Yes
