job_type == 0
is_continue == false
Spherical aberration (mm): == 1.4
Amplitude contrast: == 0.1
Pixel size (Angstrom): == 0.885
Beamtilt in X (mrad): == 0
Beamtilt in Y (mrad): == 0
Import other node types? == No
Submit to queue? == No
Import raw movies/micrographs? == Yes
Input file: == ref.mrc
Raw input files: == Movies/*.tiff
MTF of the detector: == mtf_k2_200kV.star
Are these multi-frame movies? == Yes
Voltage (kV): == 200
Minimum dedicated cores per node: == 24
Node type: == Particle coordinates (*.box, *_pick.star)
Optics group name: == opticsGroup1
Rename optics group for particles: == 
Additional arguments: == 
Queue submit command: == qsub
Standard submission script: == /public/EM/RELION/relion/bin/relion_qsub.csh
Queue name:  == openmpi
