job_type == 5
is_continue == false
Pixel size (A) == 1
Diameter background circle (pix):  == 200
Stddev for black dust removal:  == -1
Input coordinates:  == 
Cut helical tubes into segments? == Yes
Coordinates are start-end only? == Yes
Extract helical segments? == No
Invert contrast? == Yes
Normalize particles? == Yes
Submit to queue? == No
OR: re-center refined coordinates?  == Yes
OR re-extract refined particles?  == Yes
Rescale particles? == Yes
Reset the refined offsets to zero?  == No
Manually set pixel size?  == No
Particle box size (pix): == 360
Refined particles STAR file:  == Select/job017/particles.star
Use bimodal angular priors? == Yes
Number of unique asymmetrical units: == 1
Helical rise (A): == 1
Tube diameter (A):  == 200
Minimum dedicated cores per node: == 24
Number of MPI procs: == 12
Additional arguments: == 
Queue submit command: == qsub
Standard submission script: == /public/EM/RELION/relion/bin/relion_qsub.csh
Queue name:  == openmpi
Re-center on X-coordinate (in pix):  == 0
Re-center on Y-coordinate (in pix):  == 0
Re-center on Z-coordinate (in pix):  == 0
Re-scaled size (pixels):  == 256
micrograph STAR file:  == CtfFind/job003/micrographs_ctf.star
Stddev for white dust removal:  == -1
