# RELION optimiser; version 3.1-devel-commit-6bcdde
# --o Class2D/job008/run --i Extract/job007/particles.star --dont_combine_weights_via_disc --preread_images --pool 30 --pad 2 --ctf --iter 25 --tau2_fudge 2 --particle_diameter 200 --K 50 --flatten_solvent --zero_mask --oversampling 1 --psi_step 12 --offset_range 5 --offset_step 2 --norm --scale --j 6 --gpu 0:1:2:3 --pipeline_control Class2D/job008/ 

# version 30001

data_optimiser_general

_rlnOutputRootName                                    Class2D/job008/run
_rlnModelStarFile                                     Class2D/job008/run_it025_model.star
_rlnExperimentalDataStarFile                          Class2D/job008/run_it025_data.star
_rlnOrientSamplingStarFile                            Class2D/job008/run_it025_sampling.star
_rlnCurrentIteration                                            25
_rlnNumberOfIterations                                          25
_rlnDoSplitRandomHalves                                          0
_rlnJoinHalvesUntilThisResolution                         -1.00000
_rlnAdaptiveOversampleOrder                                      1
_rlnAdaptiveOversampleFraction                            0.999000
_rlnRandomSeed                                          1564139415
_rlnParticleDiameter                                    200.000000
_rlnWidthMaskEdge                                                5
_rlnDoZeroMask                                                   1
_rlnDoSolventFlattening                                          1
_rlnDoSolventFscCorrection                                       0
_rlnSolventMaskName                                   None
_rlnSolventMask2Name                                  None
_rlnBodyStarFile                                      None
_rlnTauSpectrumName                                   None
_rlnMaximumCoarseImageSize                                      -1
_rlnHighresLimitExpectation                               -1.00000
_rlnLowresLimitExpectation                                -1.00000
_rlnIncrementImageSize                                          10
_rlnDoMapEstimation                                              1
_rlnDoFastSubsetOptimisation                                     0
_rlnDoExternalReconstruct                                        0
_rlnDoStochasticGradientDescent                                  0
_rlnDoStochasticEM                                               0
_rlnSgdInitialIterations                                        50
_rlnSgdFinalIterations                                          50
_rlnSgdInBetweenIterations                                     200
_rlnSgdInitialResolution                                 35.000000
_rlnSgdFinalResolution                                   15.000000
_rlnSgdInitialSubsetSize                                       100
_rlnSgdFinalSubsetSize                                         500
_rlnSgdMuFactor                                           0.000000
_rlnSgdSigma2FudgeInitial                                 8.000000
_rlnSgdSigma2FudgeHalflife                                      -1
_rlnSgdSkipAnneal                                                0
_rlnSgdSubsetSize                                               -1
_rlnSgdWriteEverySubset                                          1
_rlnSgdStepsize                                           0.500000
_rlnDoAutoRefine                                                 0
_rlnAutoLocalSearchesHealpixOrder                                4
_rlnNumberOfIterWithoutResolutionGain                            2
_rlnBestResolutionThusFar                                 0.052966
_rlnNumberOfIterWithoutChangingAssignments                       2
_rlnDoSkipAlign                                                  0
_rlnDoSkipRotate                                                 0
_rlnOverallAccuracyRotations                              2.600000
_rlnOverallAccuracyTranslationsAngst                      2.832000
_rlnChangesOptimalOrientations                            9.190004
_rlnChangesOptimalOffsets                                 2.452008
_rlnChangesOptimalClasses                                 0.021589
_rlnSmallestChangesOrientations                           2.451956
_rlnSmallestChangesOffsets                                0.728289
_rlnSmallestChangesClasses                                       0
_rlnLocalSymmetryFile                                 None
_rlnDoHelicalRefine                                              0
_rlnIgnoreHelicalSymmetry                                        0
_rlnFourierMask                                       None
_rlnHelicalTwistInitial                                   0.000000
_rlnHelicalRiseInitial                                    0.000000
_rlnHelicalCentralProportion                              0.300000
_rlnHelicalMaskTubeInnerDiameter                          -1.00000
_rlnHelicalMaskTubeOuterDiameter                          -1.00000
_rlnHelicalSymmetryLocalRefinement                               0
_rlnHelicalSigmaDistance                                  -1.00000
_rlnHelicalKeepTiltPriorFixed                                    0
_rlnHasConverged                                                 0
_rlnHasHighFscAtResolLimit                                       0
_rlnHasLargeSizeIncreaseIterationsAgo                            0
_rlnDoCorrectNorm                                                1
_rlnDoCorrectScale                                               1
_rlnDoCorrectCtf                                                 1
_rlnDoIgnoreCtfUntilFirstPeak                                    0
_rlnCtfDataArePhaseFlipped                                       0
_rlnDoOnlyFlipCtfPhases                                          0
_rlnRefsAreCtfCorrected                                          1
_rlnFixSigmaNoiseEstimates                                       0
_rlnFixSigmaOffsetEstimates                                      0
_rlnMaxNumberOfPooledParticles                                 180
 
